package ru.itis.summerpractice24

object DetailGroupRepository {
    val groups: List<DetailGroup> = listOf(
        DetailGroup(id = 0, name = "Led Zeppelin", style = "Rock", url = "https://upload.wikimedia.org/wikipedia/ru/thumb/a/a6/LedZeppelin1969Promo.JPEG/280px-LedZeppelin1969Promo.JPEG", information =  "Led Zeppelin were an English rock band formed in London in 1968. The group comprised vocalist Robert Plant, guitarist Jimmy Page, bassist and keyboardist John Paul Jones, and drummer John Bonham. With a heavy, guitar-driven sound, they are cited as one of the progenitors of hard rock and heavy metal, although their style drew from a variety of influences, including blues and folk music. Led Zeppelin have been credited as significantly impacting the nature of the music industry, particularly in the development of album-oriented rock (AOR) and stadium rock."),
        DetailGroup(id = 1, name = "The Doors", style = "Rock", url = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/The_Doors_1968.JPG/250px-The_Doors_1968.JPG", information = "The Doors were an American rock band formed in Los Angeles in 1965, conmprising vocalist Jim Morrison, keyboardist Ray Manzarek, guitarist Robby Krieger and drummer John Densmore. They were among the most influential and controversial rock acts of the 1960s, primarily due to Morrison's lyrics and voice, along with his erratic stage persona and legal issues. The group is widely regarded as an important figure of the era's counterculture."),
        DetailGroup(id = 2, name = "Daft Punk", style = "Electronic", url = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Daftpunklapremiere2010.jpg/260px-Daftpunklapremiere2010.jpg", information = "Daft Punk were a French electronic music duo formed in 1993 in Paris by Thomas Bangalter and Guy-Manuel de Homem-Christo. They achieved early popularity in the late 1990s as part of the French house movement, combining elements of house music with funk, disco, techno, rock and synth-pop.[1] The duo garnered further acclaim and commercial success and are now regarded as one of the most influential acts in dance music history"),
        DetailGroup(id = 3, name = "Black Sabbath", style = "Metal", url = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Black_Sabbath_%281970%29.png/250px-Black_Sabbath_%281970%29.png", information = "Black Sabbath were an English rock band formed in Birmingham in 1968 by guitarist Tony Iommi, drummer Bill Ward, bassist Geezer Butler and vocalist Ozzy Osbourne. They are often cited as pioneers of heavy metal music.[1] The band helped define the genre with their first three albums Black Sabbath, Paranoid (both 1970) and Master of Reality (1971). Following Osbourne's departure in 1979, the band underwent multiple line-up changes, with Iommi being the only constant member throughout their history."),
        DetailGroup(id = 4, name = "Queen", style = "Rock", url = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Queen_–_montagem_–_new.png/250px-Queen_–_montagem_–_new.png", information = "Queen are a British rock band formed in London in 1970 by Freddie Mercury (lead vocals, piano), Brian May (guitar, vocals), and Roger Taylor (drums, vocals), later joined by John Deacon (bass). Their earliest works were influenced by progressive rock, hard rock, and heavy metal, but the band gradually ventured into more conventional and radio-friendly works by incorporating further styles, such as arena rock and pop rock."),
        DetailGroup(id = 5, name = "AC/DC", style = "Rock", url = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/ACDC_In_Tacoma_2009.jpg/250px-ACDC_In_Tacoma_2009.jpg", information = "AC/DC are an Australian rock band formed in 1973. It was founded by brothers Malcolm Young on rhythm guitar and Angus Young on lead guitar. Their current line-up comprises Angus, bass guitarist Cliff Williams, drummer Phil Rudd, lead vocalist Brian Johnson and rhythm guitarist Stevie Young, nephew of Angus and Malcolm. Their music has been variously described as hard rock, blues rock and heavy metal, but the band calls it simply \"rock and roll\". They are cited as a formative influence on the new wave of British heavy metal bands, such as Def Leppard and Saxon. AC/DC were inducted into the Rock and Roll Hall of Fame in 2003."),
        DetailGroup(id = 6, name = "50 Cent", style = "Hip Hop", url = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/50_Cent_in_2018.png/274px-50_Cent_in_2018.png", information = "Curtis James Jackson III (born July 6, 1975),[3] known professionally as 50 Cent,[n 1] is an American rapper, actor, television producer, and businessman. Born in South Jamaica, a neighborhood of Queens, Jackson began pursuing a musical career in 1996. In 1999-2000, he recorded his \"debut\" album Power of the Dollar for Columbia Records; however, he was struck by nine bullets during a shooting in May 2000, causing its release to be cancelled and Jackson to be dropped from the label. His 2002 mixtape, Guess Who's Back? was discovered by Detroit rapper Eminem, who signed Jackson to his label Shady Records, an imprint of Dr. Dre's Aftermath Entertainment and Interscope Records that same year.")
        )
    fun convertListToGroup(listWithDetailGroup: List<DetailGroup>): List<Group> {
        val listWithGroup = mutableListOf<Group>()

        for (detailGroup in listWithDetailGroup) {
            val group = Group(detailGroup.id, detailGroup.name, detailGroup.style, detailGroup.url)
            listWithGroup.add(group)
        }

        return listWithGroup
    }
}